
export const SETORDERREQUESTPARAM  = 'SETORDERREQUESTPARAM'; 
export const CURRENTORDERS  = 'CURRENTORDERS'; 
export const COMPLATEDORDERS  = 'COMPLATEDORDERS'; 
export const WARRANTYORDERS  = 'WARRANTYORDERS'; 
export const ORDERDETAILS  = 'ORDERDETAILS'; 
export const ORDERSUCCESS  = 'ORDERSUCCESS'; 
export const CANCELEDORDER  = 'CANCELEDORDER'; 
export const ORDERSTATUS  = 'ORDERSTATUS'; 
export const UNSETSUCCESSORDER  = 'UNSETSUCCESSORDER'; 
export const PROMOCODE  = 'PROMOCODE'; 
export const ENGINEERPROFILE  = 'ENGINEERPROFILE'; 
export const ENGINEERREVIEWS  = 'ENGINEERREVIEWS'; 
export const SHIPPEDDEVICES  = 'SHIPPEDDEVICES'; 
export const RECEIVEDDEVICE  = 'RECEIVEDDEVICE'; 
export const WARRENTYDIALOG  = 'WARRENTYDIALOG'; 


